import Footer from "@/components/Shared/Footer";
import Navbar from "@/components/Shared/Navbar";
import Provider from "@/provider/Provider";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";
import "../globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Edupy academy",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <Provider>
                    <Navbar />
                    {children}
                    <Footer />
                </Provider>
                <Toaster />
            </body>
        </html>
    );
}
